#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# two_springs_plot.py
#
# purpose:  solve a system of differential equations
# author:   Filipe P. A. Fernandes
# e-mail:   ocefpaf@gmail
# web:      http://ocefpaf.tiddlyspot.com/
# created:  27-Oct-2010
# modified: Wed 27 Oct 2010 12:00:08 PM EDT
#
# obs: http://www.scipy.org/Cookbook/CoupledSpringMassSystem
#

#
# two_springs_plot.py
#
"""Plot the solution that was generated by two_springs_solver.py."""

from pylab import *
from numpy import *
from matplotlib.font_manager import FontProperties

data = loadtxt('two_springs.dat')
t  = data[:,0]
x1 = data[:,1]
y1 = data[:,2]
x2 = data[:,3]
y2 = data[:,4]

figure(1,figsize=(6,4)).subplots_adjust(bottom=0.11)

xlabel('t')
grid(True)
hold(True)
lw = 1

plot(t,x1,'b',linewidth=lw)
plot(t,x2,'g',linewidth=lw)

legend((r'$x_1$',r'$x_2$'),prop=FontProperties(size=16))
title('Mass Displacements for the Coupled Spring-Mass System')
savefig('two_springs.png',dpi=72)
